
server:
  port: 7774

spring:
  application:
    name: consumer


  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        dashboard: localhost:8888

feign:
  sentinel:
    enabled: true



  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411
    service:
      name: consumer
  sleuth:
    sampler:
      probability: 1   #设置采样率默认为 0.1 注意之前的版本是percentage 新版本中更换为 probability